version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/main/java/Dockerfile.backend
    ports:
      - "8080:8080"
    restart: always
  frontend:
    build:
      context: ./src/main/moivo_react
      dockerfile: ./src/main/moivo_react/Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always
