version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/main/java/Dockerfile.backend
      args:
        JAR_FILE: build/libs/Moivo-0.0.1-SNAPSHOT.jar
    ports:
      - "9090:8080"
    restart: always
  frontend:
    build:
      context: ./src/main/moivo_react
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    restart: always
