spring: # test
  config:
    import:
      - classpath:/application-mysql.properties
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test
            client-secret: test
            redirect-uri: test
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname    # 닉네임
              - profile_image       # 프로필 사진
              - account_email       # 이메일
            client-name: Kakao
            provider: kakao

        provider:
          kakao:
            authorization-uri: test
            token-uri: test
            user-info-uri: test
            user-name-attribute: id

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1

  datasource:
    # MySQL - NAVER Cloud 설정
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: -1 # 파일당 최대 크기 (-1은 무제한)
      max-request-size: -1 # 요청 전체 최대 크기 (-1은 무제한)

  mail:
    host: smtp.gmail.com # 12/11 16:57 조강민
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            enable: false

ncp:
  storage:
    access-key: test
    secret-key: test
    region: kr-standard
    endpoint: test


jwt:
  secret: 1234567890abcdef1234567890abcdef
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일

management:
  endpoints:
    web:
      exposure:
        include: beans # Actuator의 Bean 목록 확인

logging:
  level:
    org.springframework.security: DEBUG

#application.yml에 등록하면 git에 올릴때 인증정보가 노출되는 문제가 있어서
#노출되지 않길 원한다면 별도의 yml을 생성하여 인증정보만 관리하도록 하여 이를 .gitignore에서 처리
#yml은 resouce 디렉토리 하위에 google or naver.yml 파일생성.
#.gitignore에
###인증정보 제외
#/src/main/resources/google or naver.yml 추가